name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Swiftlint
      uses: norio-nomura/action-swiftlint@3.1.0
      env:
          DIFF_BASE: ${{ github.base_ref }}
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
