name: Swift

env:
  DANGER_SWIFT_PATH: ${{ github.workspace }}/danger-swift
  MINT_PATH: ${{ github.workspace }}/mint
  SWIFLINT_PATH: ${{ github.workspace }}/swiftlint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Cache Mint
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-mint
        path: ${{ env.MINT_PATH }}

    - name: Cache Danger Swift
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-danger-swift
        path: ${{ env.DANGER_SWIFT_PATH }}

    - name: Cache Mint packages
      uses: actions/cache@v1
      with:
        path: ${{ env.MINT_PATH }}
        key: ${{ runner.os }}-mint-dependencies-${{ hashFiles('**/Mintfile') }}

    - name: Bootstrap
      run: make setup

    - name: Danger
      if: ${{ github.event_name == 'pull_request' }}
      run: danger-swift ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
