name: Swift

env:
  MINT_PATH: ${{ github.workspace }}/mint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Cache Mint packages
      uses: actions/cache@v1
      with:
        path: ${{ env.MINT_PATH }}
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: ${{ runner.os }}-mint-

    - name: Bootstrap
      run: make setup

    - name: Swiflint
      run: swiftlint

    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
